# Generated by Django 3.2.23 on 2023-11-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231112_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='describtion',
            new_name='description',
        ),
    ]
